[[repos]]
name = "ant-design-icons"
url = "git@github.com:ant-design/ant-design-icons.git"
git_ref = "4ab94f341f63deccd1b7fa296f47ed88b818a3fe" # v4.3.1

[repos.paths]
Outlined = "packages/icons-svg/svg/outlined"
Filled = "packages/icons-svg/svg/filled"

[[repos]]
name = "bootstrap-icons"
url = "git@github.com:twbs/icons.git"
git_ref = "8d7bc695fb407627378cb184976b348e6a128d59" #v1.11.1

[repos.paths]
_ = "icons"

[[repos]]
name = "boxicons"
url = "git@github.com:atisawd/boxicons.git"
git_ref = "9ffa9136e8681886bb7bd2145cd4098717ce1c11" # 2.1.4

[repos.paths]
Logo = "svg/logos"
Regular = "svg/regular"
Solid = "svg/solid"

[[repos]]
name = "charm-icons"
url = "git@github.com:jaynewey/charm-icons.git"
git_ref = "8115fa8fd3e1008815fe2734117e37d2b30882f1" #v0.18.0

[repos.paths]
_ = "icons"

[[repos]]
name = "codicons"
url = "git@github.com:microsoft/vscode-codicons.git"
git_ref = "080608815546b776a6397e9566d47b5996a78546" # 0.0.35

[repos.paths]
_ = "src/icons"

[[repos]]
name = "css.gg"
url = "git@github.com:astrit/css.gg.git"
git_ref = "fd750c9df1b1caa060b6321da9b28dfd32028d83" # 2.1.1

[repos.paths]
_ = "icons/svg"

[[repos]]
name = "feather"
url = "git@github.com:feathericons/feather.git"
git_ref = "ff2923ecea24c57ff39447cd91ee7561b92d765f" # v4.29.1

[repos.paths]
_ = "icons"

[[repos]]
name = "font-awesome"
url = "git@github.com:FortAwesome/Font-Awesome.git"
git_ref = "f0c25837a3fe0e03783b939559e088abcbfb3c4b" # 6.4.2

[repos.paths]
Brand = "svgs/brands"
Regular = "svgs/regular"
Solid = "svgs/solid"

[[repos]]
name = "heroicons"
url = "git@github.com:tailwindlabs/heroicons.git"
git_ref = "f64c10b59dcd6417732a984ce4376bed13799485" # v2.0.18

[repos.paths]
Outline = "optimized/24/outline"
Solid = "optimized/24/solid"
Mini = "optimized/20/solid"

[[repos]]
name = "ionicons"
url = "git@github.com:ionic-team/ionicons.git"
git_ref = "df6d6f8aebca616df50f090f46f655cb0d75ec68" # v7.2.1

[repos.paths]
_ = "src/svg"

[[repos]]
name = "lucide"
url = "git@github.com:lucide-icons/lucide.git"
git_ref = "207ff6c487ac0ab6144aec10e2244045fc24062f" # v0.292.0

[repos.paths]
_ = "icons"

[[repos]]
name = "microns"
url = "git@github.com:stephenhutchings/microns.git"
git_ref = "2d68ae57e4c9938e27ee3f8c9600476c49571dc1" # v1.1.3

[repos.paths]
_ = "svg"

[[repos]]
name = "octicons"
url = "git@github.com:primer/octicons.git"
git_ref = "6bc78de32be1a218a69e10a731072331ba94e7f9" # v19.8.0

[repos.paths]
_ = "icons"

[[repos]]
name = "remixicon"
url = "git@github.com:Remix-Design/RemixIcon.git"
git_ref = "f428a68c64c9ab96d019c139b63f85f4d6e9fb3a" # v3.5.0

[repos.paths]
Arrows = "icons/Arrows"
Buildings = "icons/Buildings"
Business = "icons/Business"
Communication = "icons/Communication"
Design = "icons/Design"
Development = "icons/Development"
Device = "icons/Device"
Document = "icons/Document"
Editor = "icons/Editor"
Finance = "icons/Finance"
HealthMedical = "icons/Health & Medical"
Logos = "icons/Logos"
Map = "icons/Map"
Media = "icons/Media"
Others = "icons/Others"
System = "icons/System"
UserFaces = "icons/User & Faces"
Weather = "icons/Weather"

[[repos]]
name = "simple-icons"
url = "git@github.com:simple-icons/simple-icons.git"
git_ref = "fb9a50374d5bdc2c2bfdf20119fbf4cff71f6c14" # 9.19.1

[repos.paths]
_ = "icons"

[[repos]]
# shallow = true
name = "tabler-icons"
url = "git@github.com:tabler/tabler-icons.git"
git_ref = "93e971c34c184c76b43413004a237a1e2902c58f" # v2.40.0

[repos.paths]
_ = "icons"
