[[repos]]
name = "ant-design-icons"
url = "github.com/ant-design/ant-design-icons.git"
git_ref = "4ab94f341f63deccd1b7fa296f47ed88b818a3fe" # v4.3.1
[repos.paths]
Outlined = "packages/icons-svg/svg/outlined"
Filled = "packages/icons-svg/svg/filled"

[[repos]]
name = "bootstrap-icons"
url = "github.com/twbs/icons.git"
git_ref = "108565f11f099f177b31929e3eafc2c8d497fcd1" #v1.11.2
[repos.paths]
_ = "icons"

[[repos]]
name = "boxicons"
url = "github.com/atisawd/boxicons.git"
git_ref = "9ffa9136e8681886bb7bd2145cd4098717ce1c11" # 2.1.4
[repos.paths]
Logo = "svg/logos"
Regular = "svg/regular"
Solid = "svg/solid"

[[repos]]
name = "charm-icons"
url = "github.com/jaynewey/charm-icons.git"
git_ref = "8115fa8fd3e1008815fe2734117e37d2b30882f1" #v0.18.0
[repos.paths]
_ = "icons"

[[repos]]
name = "codicons"
url = "github.com/microsoft/vscode-codicons.git"
git_ref = "080608815546b776a6397e9566d47b5996a78546" # 0.0.35
[repos.paths]
_ = "src/icons"

[[repos]]
name = "css.gg"
url = "github.com/astrit/css.gg.git"
git_ref = "fd750c9df1b1caa060b6321da9b28dfd32028d83" # 2.1.1
[repos.paths]
_ = "icons/svg"

[[repos]]
name = "feather"
url = "github.com/feathericons/feather.git"
git_ref = "ff2923ecea24c57ff39447cd91ee7561b92d765f" # v4.29.1
[repos.paths]
_ = "icons"

[[repos]]
name = "font-awesome"
url = "github.com/FortAwesome/Font-Awesome.git"
git_ref = "deeea78c52bfe00b6e251ffddccf5570d5fdb05e" # 6.5.1
[repos.paths]
Brand = "svgs/brands"
Regular = "svgs/regular"
Solid = "svgs/solid"

[[repos]]
name = "heroicons"
url = "github.com/tailwindlabs/heroicons.git"
git_ref = "88ab3a0d790e6a47404cba02800a6b25d2afae50" # v2.1.1
[repos.paths]
Outline = "optimized/24/outline"
Solid = "optimized/24/solid"
Mini = "optimized/20/solid"

[[repos]]
name = "ionicons"
url = "github.com/ionic-team/ionicons.git"
git_ref = "fccc2606274ac79c420a15df210e9649449a2acb" # v7.2.2
[repos.paths]
_ = "src/svg"

[[repos]]
name = "lucide"
url = "github.com/lucide-icons/lucide.git"
git_ref = "5ecfd613970ddbf2db7e2def5422ffdb3e10d61e" # v0.302.0
[repos.paths]
_ = "icons"

[[repos]]
name = "microns"
url = "github.com/stephenhutchings/microns.git"
git_ref = "e6e6f4fa7307a27b2f780957de504a87f6d3d3c9" # v1.1.4
[repos.paths]
_ = "svg"

[[repos]]
name = "octicons"
url = "github.com/primer/octicons.git"
git_ref = "6bc78de32be1a218a69e10a731072331ba94e7f9" # v19.8.0
[repos.paths]
_ = "icons"

[[repos]]
name = "remixicon"
url = "github.com/Remix-Design/RemixIcon.git"
git_ref = "1304a1f3d7cf127401918213e462d021a168d209" # v4.0.0
[repos.paths]
Arrows = "icons/Arrows"
Buildings = "icons/Buildings"
Business = "icons/Business"
Communication = "icons/Communication"
Design = "icons/Design"
Development = "icons/Development"
Device = "icons/Device"
Document = "icons/Document"
Editor = "icons/Editor"
Finance = "icons/Finance"
Food = "icons/Food"
HealthMedical = "icons/Health & Medical"
Logos = "icons/Logos"
Map = "icons/Map"
Media = "icons/Media"
Others = "icons/Others"
System = "icons/System"
UserFaces = "icons/User & Faces"
Weather = "icons/Weather"

[[repos]]
name = "simple-icons"
url = "github.com/simple-icons/simple-icons.git"
git_ref = "8b9040cf7384ba65ef8d4d904a129bed928e8c38" # 10.4.0
[repos.paths]
_ = "icons"

[[repos]]
# shallow = true
name = "tabler-icons"
url = "github.com/tabler/tabler-icons.git"
git_ref = "ffed949675ec8b825e7a6eaa45166a83bc6f8ff8" # v2.44.0
[repos.paths]
_ = "icons"
