[package]
name = "icons_preview"
edition = "2021"
version = "1.0.0"
publish = false

[dependencies]
icon_sets = { path = "../icon_sets" }
leptos = { version = "0.5.2", features = ["csr"] }
leptos-use = "0.8.1"
web-sys = { version = "0.3.65", features = ["Navigator", "Clipboard"] }
