on:
  push:
  pull_request:

name: Continuous Integration

jobs:
  clippy:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings --cfg=web_sys_unstable_apis
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: clippy

      - run: cargo clippy --all --all-features
  fmt:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings --cfg=web_sys_unstable_apis
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt

      - run: cargo fmt --all --check
  generate:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt

      - run: |
          wget https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-musl.tgz
          tar -xvf cargo-binstall-x86_64-unknown-linux-musl.tgz
          cp cargo-binstall /usr/local/cargo/bin
          cargo binstall cargo-make -y
          cargo binstall leptosfmt -y

      - name: generate
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: generate

      - run: |
          git diff --quiet --exit-code

          if [[ $? -ne 0 ]]; then
            echo "::error::uncommitted changes exist"
            exit 1
          fi
