on:
  push:
  pull_request:

name: Continuous Integration

jobs:
  clippy:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings --cfg=web_sys_unstable_apis
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: clippy

      - run: cargo clippy --all --all-features

  generate:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-binstall,cargo-make

      - run: |
          cargo binstall leptosfmt -y

      - run: |
          cargo make prep
        env:
          REPO_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          git diff --exit-code
